src/components/pdpa/index.tsx

feat: pdpa modal

---

src/app/ending/page.tsx
src/app/reward/page.tsx
src/app/rewarddone/page.tsx
src/app/staff/home/page.tsx
src/app/staff/info/page.tsx
src/app/stamp/page.tsx
src/components/MenuIcon.tsx
src/components/MenuList.tsx
src/components/TwoCircleMenu.tsx
src/context/AuthContext.tsx
src/utils/reward.ts

- change TwoCircleMenu to MenuList
- add reward button to MenuList
- add MenuList to stamp page and result page (ending page right now)

feat: reward system

---

src/components/rpkm/Footer.tsx
tailwind.config.ts

Dong be/fdr 68 footer

---

src/utils/auth.ts

fix: refresh token

---

Dockerfile

fix: Dockerfile add ARGS

---

.github/workflows/build-deploy.yml

fix: build image

---

.github/workflows/build-deploy.yml

dev prod pipeline

---

.github/workflows/build-deploy.yml

dev prod tags

---

.github/workflows/build-deploy.yml

Dev prod pipeline add |

---

src/context/AuthContext.tsx

add: prevent re-login

---

src/app/(main)/register/page.tsx

fix register

---

src/app/(main)/register-done/page.tsx
src/components/(main)/finish-register/flowers.tsx
src/components/(main)/home/CustomButton.tsx
src/components/firstdate/home/modal/OTPModal.tsx

Tee fix otp style

---

src/app/firstdate/reward/page.tsx

fix receive gift dont update

---

.devcontainer/devcontainer.json
.github/dependabot.yml
.gitignore
.vscode/settings.json
next.config.mjs
package.json
pnpm-lock.yaml
src/components/(main)/register/UploadProfilePicture.tsx
src/components/UserCard.tsx

feat: add sharp to production

---

src/app/healthz/route.ts

hotfix: unused

---

src/app/(main)/staff/edit/page.tsx

- 
- 
- Edit major for staff (always 21)
-

fix: hotfix edit major for staff

---

src/components/(main)/register/UploadProfilePicture.tsx

limit file input

---

src/components/firstdate/MenuList.tsx

fix menulist

---

src/components/rpkm/Sidebar/Menu.tsx

add logout button

---

src/context/BaanContext.tsx

prevent select baan in selected order

---

src/components/rpkm/Sidebar/Menu.tsx
src/components/rpkm/Sidebar/UserInfo.tsx

disable sidebar

---

next.config.mjs
src/app/(main)/home/page.tsx
src/components/(main)/home/CustomButton.tsx
src/utils/time.ts

fix: ntp time

---

src/components/(main)/home/CustomButton.tsx

fix: time un match

---

public/alert.svg
src/components/rpkm/Baan/Section/BaanButtonsSection.tsx

add confirm modal content

---

src/app/rpkm/activities/home/page.tsx

remove local activities

---

src/utils/stamp.ts

add answer to club stamp

---

.github/workflows/build-deploy.yml
.github/workflows/send-message.yml

- add discord message when pr
- 
- 
-

wf add message

---

next.config.mjs

fix; next.config

---

src/components/rpkm/Sidebar/UserInfo.tsx

fix: show baan's line on announce time

---

src/components/rpkm/Sidebar/FreshyNightLink.tsx

fix: freshy night confirm event typo

---

src/app/rpkm/freshy-night/coming-soon/page.tsx
src/app/rpkm/freshy-night/register/page.tsx

Dong/ Add Poster

---

src/context/AuthContext.tsx

fix: route protect cannot register

---

package.json
pnpm-lock.yaml
src/components/rpkm/staff/home/qrscanner/QRScanner.tsx

change: react qr reader lib tp html5 qr reader lib

---

src/app/rpkm/staff/home/page.tsx

remove 'หรือ' from staff home page

---

package.json
pnpm-lock.yaml
src/app/rpkm/staff/home/page.tsx

test: moment js

---

src/components/rpkm/staff/home/qrscanner/QRScanner.tsx
src/components/rpkm/staff/home/qrscanner/style.css

fix: remove qr shaded region
